### ISSUE TITLE
[F] More Rotation

### ISSUE THREAD

**Issue by Noitarud** [therealbluepandabear/PixaPencil_Classic#259]
If you can add stretch and skew as seen in MSPaint, you can add in more versatile rotation than simple 90° steps.
I have two versions for you to try:
Θ is Angle in radians, ±178° max. Paint only accepts integers.

First one by user IronMortality (2,3 can be done together in Paint)
1. Horizontal skew by Angle
2. Vertical stretch by 1/cos(θ)² (write decimal as %)
3. Vertical skew by negative Angle
4. Horiz+Vert stretch by cos(θ)

Second by Murrogh (1,2 together).
0. Note ±>45° may be distorted more. Rotate 90/180/270 first.
1. Horizontal skew by Angle/2
2. Vertical skew by negative atan(sin(θ)) in degrees (not radians)
3. Horizontal skew by Angle/2

Enjoy!

**Comment by therealbluepandabear** [comment]
Do you mean the rotation of the **bitmap** itself or the rotation of the **canvas**? I am thinking of adding custom bitmap rotation using RotSprite, but for canvas rotation I don't see a point in having custom rotation.

**Comment by Noitarud** [comment]
The features i am referring to are in older paint (98-XP, maybe newer but not the present 3D version).
I do not know the difference between those terms, i will guess "canvas", so i will describe thus for 45° (Murrogh):

1. Draw square/rect on the canvas
2. On the menu bar, go: Image > Stretch/Skew… (Ctrl+W)
3. A)Enter 23 for skew Horizontal; B) -35 for skew Vertical; C) Ok
4. Repeat step 2 and 3A; Ok

Besides all white space around it, your drawing will be rotated.

**Comment by Noitarud** [comment]
i would think Stretching and skewing are very elementary actions, the steps together gives rotation. Then the user would need to be queried if the canvas size should be adjusted (#274 #284). Also cool (probably slow) when using with symmetry 🌺[they drew that image incorrectly].

Stretch is easy enough.
Skew's displacement is found with Tan(radians) added to each successive line.

**Comment by Noitarud** [comment]
Here is another resource from a completely different perspective: http://www.helixsoft.nl/articles/circle/sincos.htm
