### ISSUE TITLE
[I] Add some extra Palettes

### ISSUE THREAD

**Issue by Noitarud** [therealbluepandabear/PixaPencil_Classic#261]
I notice you are using a colour selection from Wikipedia's "List of colors: A–F" these colours are apparently not using discrete steps and that list is poorly representative of the spectrum and is using irregular colour codes (and artists names for them). I would like regular colours for my diagrams  (eg 16bit uses 0/50/100% of R,G,B,RG,GB,BR,RGB and 75% of RGB). I know I can enter them but this is an opportunity to add another palette, and this suggestion could inspire a different picker #227 (else additional).

Can you create a palette based on divisions of 255? Ie based on a cubic matrix (cubic for RGB).

Here is an example of a (red/green) square matrix with 1/3 steps

XXX OOO ---OOR---ORR----RRR
OOO --Blk  ----x---------x-------red
OOG ----x----dkYell-----x-----orange
OGG ----x-------x---------x----Lt orange
GGG  Green leaf?  Lime  yellow

More kinds:
1. Perhaps you can use the colours and names at https://en.wikipedia.org/wiki/Hue#24_hues_of_HSL/HSV (note uses 0/15.6/31/75/100% to define hue, instead of fractions of 255 that i thought were needed, list uses circular degrees at 15° intervals, satisfactory for me, unless you want to let the user build their own with a different interval). Tint/tones/shades (whiteness/greys/blackness) appear to be regarded as linear on the other pages.
2. [The palette implied here could be useful as another option https://en.wikipedia.org/wiki/Natural_Color_System, but is based on perception, not sure about mixing to get the wider variety of colours.] It says proprietary so no.

**Comment by therealbluepandabear** [comment]
Thanks for the input, I will revamp the default palette sometime in the future.
