### ISSUE TITLE
Colour Multientry

### ISSUE THREAD

**Issue by Noitarud** [therealbluepandabear/PixaPencil_Classic#263]
While entering as i said in #261, i am finding entering tedious, repeating these steps: •+Add •press Hex •tap in the address •Done

Options:
•Have an empty box below for 'next' and create more if the last gets used (columns for rgb).
•next/last key, also lets review of existing entries.
• or both, show table(RGB)/list(Hex). Allows comparison of new and existing.

**Comment by therealbluepandabear** [comment]
Sorry, not sure what you mean, please provide an image/sketch.

**Comment by Noitarud** [comment]
I will illustrate the third since it allows comparison between entries. I didn't illustrate a button for adding a line (sort can be there if required)
![IMG_20221003_163746](https://user-images.githubusercontent.com/98794719/193516096-5cdf3731-0783-465c-90cc-30d905db8419.jpg)

Doing many can be done quick and you can amend typos too. The slow part after that is typing letters or numbers, since I am using AnySoftKeyboard which has a letters layout (numbers if each held) or a numbers+!@#$%^&… layout without letters that I can switch between. it does have a password layout which will show letters and numbers together that you could specify I assume.

**Comment by therealbluepandabear** [comment]
I understand the feature that you want, it seems _extremely_ difficult to add.

**Comment by Noitarud** [comment]
easier: import text doc. Can make lists of figures with spreadsheet.
